item_bronze = {
	--30 Lingots de Rarium : 3,33%
	"xtraores:rarium_bar 30",
	--25 Noclip Blocks : 13,33%
	"noclip_block:noclip_block 25",
	"noclip_block:noclip_block 25",
	"noclip_block:noclip_block 25",
	"noclip_block:noclip_block 25",
	--10 Bannières de Parabellum : 13,33%
	"parabellum:banner 10",
	"parabellum:banner 10",
	"parabellum:banner 10",
	"parabellum:banner 10",
	--150 Trap Spikes Major : 20%
	"bobblocks:trap_spike_major 150",
	"bobblocks:trap_spike_major 150",
	"bobblocks:trap_spike_major 150",
	"bobblocks:trap_spike_major 150",
	"bobblocks:trap_spike_major 150",
	"bobblocks:trap_spike_major 150",
	--100 Dynamite Big : 20%
	"grenade:dynamitebig 100",
	"grenade:dynamitebig 100",
	"grenade:dynamitebig 100",
	"grenade:dynamitebig 100",
	"grenade:dynamitebig 100",
	"grenade:dynamitebig 100",
	--100 Billets de 50 : 30%
	"currency:minegeld_50 100",
	"currency:minegeld_50 100",
	"currency:minegeld_50 100",
	"currency:minegeld_50 100",
	"currency:minegeld_50 100",
	"currency:minegeld_50 100",
	"currency:minegeld_50 100",
	"currency:minegeld_50 100",
	"currency:minegeld_50 100"
	}
item_steel = {
	"grenade:dynamitebig 100",
	"bobblocks:trap_spike_major 150",
	"default:obsidian 300",
	"mobs_monster:oerki 20",
	"xdecor:cobweb 500"
}
item_palladium = {
	"dmobs:unobtanium_bar",
	"xtraores:orichalcum_bar 10",
	"xtraores:orichalcum_bar 10",
	"banners:power_banner",
	"banners:power_banner",
	"banners:power_banner",
	"banners:power_banner",
	"xtraores:palladium_bar 5",
	"xtraores:palladium_bar 5",
	"xtraores:palladium_bar 5",
	"xtraores:palladium_bar 5",
	"parabellum:head_wither_skeleton 9",
	"parabellum:head_wither_skeleton 9",
	"parabellum:head_wither_skeleton 9",
	"parabellum:head_wither_skeleton 9",
	"parabellum:head_wither_skeleton 9",
	"parabellum:head_wither_skeleton 9",
	"currency:minegeld_50 120",
	"currency:minegeld_50 120",
	"currency:minegeld_50 120",
	"currency:minegeld_50 120",
	"currency:minegeld_50 120",
	"currency:minegeld_50 120",
	"currency:minegeld_50 120",
	"currency:minegeld_50 120"
}
item_ulti = {
	"xtraores:ultigemite_bar",
	"xtraores:ultigemite_bar",
	"xtraores:orichalcum_bar 10",
	"xtraores:orichalcum_bar 10",
	"xtraores:orichalcum_bar 10",
	"dmobs:unobtanium_bar",
	"dmobs:unobtanium_bar",
	"dmobs:unobtanium_bar",
	"dmobs:unobtanium_bar",
	"banners:power_banner",
	"banners:power_banner",
	"banners:power_banner",
	"banners:power_banner",
	"banners:power_banner",
	"banners:power_banner",
	"parabellum:head_wither_skeleton 12",
	"parabellum:head_wither_skeleton 12",
	"parabellum:head_wither_skeleton 12",
	"parabellum:head_wither_skeleton 12",
	"parabellum:head_wither_skeleton 12",
	"parabellum:head_wither_skeleton 12",
	"currency:minegeld_50 140",
	"currency:minegeld_50 140",
	"currency:minegeld_50 140",
	"currency:minegeld_50 140",
	"currency:minegeld_50 140",
	"currency:minegeld_50 140",
	"currency:minegeld_50 140",
	"currency:minegeld_50 140",
	}
